class PluginSettings(object):
    SHARED_PARTITION = 'slurm.SHARED_PARTITION'
    CRONTAB_PARTITION = 'slurm.CRONTAB_PARTITION'
    API_URL = 'slurm.API_URL'
    SLURM_PARTITION = 'slurm.PARTITION'
    SLURM_NODES = 'slurm.NODES'
    SLURM_TASKS = 'slurm.TASKS'
    SLURM_CPU = 'slurm.CPU'
    SLURM_MEMERY = 'slurm.MEMERY'
    SLURM_TIME = 'slurm.TIME'
